### ISSUE TITLE
can you extend the range of sersic index?

### ISSUE THREAD

**Issue by lirui10590** [glenco/lensed#249]
I am using LENSED to fit the BELLS(a project like SLACS), As for some of the lens system，the sersic index often out of the range 0.5<n<8. So I want to ask if you can using this formula. 
  
        if nser >= 0.36:             # from Ciotti & Bertin 1999, truncated to n^-3
	   b=2.0*nser-1./3+4./(405.*nser)+46./(25515.*nser**2.)+131./(1148175.*nser**3.)
	else:                     # from MacArthur et al. 2003
	  b=0.01945-0.8902*nser+10.95*nser**2.-19.67*nser**3.+13.43*nser**4.
I have tried  to use the formula above to replace the formula
        b≈1.9992n−0.3271
But it doesn't work.

**Comment by ntessore** [comment]
This formula is already implemented in the long-standing pull request #242, which I will merge now after the checks run. Once it is merged, please do a `git pull` and try whether this solves the issue.

**Comment by ntessore** [comment]
PR #242 is now merged, @lirui10590 please see if that works for you.

**Comment by lirui10590** [comment]
It works for me,Thanks very much!

**Comment by lirui10590** [comment]
It works for me,thanks a lot!

在2016-12-12 19:38:14，李瑞lirui@ynao.ac.cn写道：

PR #242 is now merged, @lirui10590 please see if that works for you.
