### ISSUE TITLE
There is no negative values in my weight fits file, but the new version1.3.1 warn me  that some pixel weights are not positive numbers

### ISSUE THREAD

**Issue by lirui10590** [glenco/lensed#263]
There is no negative values in my weight fits file, but the new version1.3.1 warn me  that some pixel weights are not positive numbers, while the version 1.2.0 have no warning. I didn't find the reasons.

**Comment by ntessore** [comment]
Could you attach a config file?

**Comment by lirui10590** [comment]
this is my config file

image   = image.fits
weight  = invvar.fits
psf     = psf.fits
gain    = 1.5
nlive   = 100
output  = true
root    = chains/slacs

[objects]
host   = sersic
lens   = sie
source = sersic

[priors]
host.x     = unif 38 44
host.y     = unif 38 44
host.r     = unif 10 60
host.mag   = unif -15 5
host.n     = unif 1 8
host.q     = unif 0.5 1
host.pa    = wrap unif 0 180
lens.x     = unif 37 45
lens.y     = unif 37 45
lens.r     = unif 7 30
lens.q     = unif 0.1 1
lens.pa    = wrap unif 0 180
source.x   = unif 37 45
source.y   = unif 37 45
source.r   = unif 0.1 1.5
source.mag = unif -5 5
source.n   = unif 0.01 15
source.q   = unif 0.1 1
source.pa  = wrap unif 0 180

**Comment by lirui10590** [comment]
this is all of my files
[0237.zip](https://github.com/glenco/lensed/files/921178/0237.zip)

**Comment by ntessore** [comment]
fixed in v1.3.2 which is coming through now
