### ISSUE TITLE
New models

### ISSUE THREAD

**Issue by fabiobg83** [glenco/lensed#65]
We should add the possibility of using other lens models, such as NSIE or NFW at least.

EDIT: Let's try to make a list of the lens models which are needed before we submit the paper.
- [X] SIE
- [x] NSIE
- [x] SIS
- [x] NSIS
- [ ] Power Law 
- [ ] NFW
- [ ] Pseudo-NFW
- [x] Point Mass

And what about sources?
- [X] Sersic 
- [x] De Vacouleurs
- [x] Exponential Disk
- [x] Gaussian

**Comment by ntessore** [comment]
Closing this, as I think we have a good selection of common objects.
