### ISSUE TITLE
Exchange symmetry for sources

### ISSUE THREAD

**Issue by ntessore** [glenco/lensed#94]
When multiple sources on the same plane have the same priors, there is an exchange symmetry between any two of them. This will make the posterior multi-modal without any benefit, and can potentially slow down the computation.

We should come up with a way to detect this and, ideally, work around it.

**Comment by ntessore** [comment]
The ability to put image plane priors on the observed position of sources should pretty much get rid of this problem. What do you think @rbmetcalf @fabiobg83 ?

**Comment by rbmetcalf** [comment]
If you stick to image based priors and you don't try to fit two profiles to the same image I agree.
